### ISSUE TITLE
Enable redis persistance

### ISSUE THREAD

**Issue by amiru3f** [muhammadmnorouzi/MemoRedis#1]
https://github.com/muhammadmnorouzi/MemoRedis/blob/3f1c65914725e01e08bf0c3620fb01092679e3f4/docker-compose.yml#L23

Dear Muhammad I highly recommend you not to use redis as a primary persistent db. Anyway, I guess you have forgotten to enable your redis persistence in your production composer file.

**Comment by muhammadmnorouzi** [comment]
Hello and thank you for your helpful reviews.
With no new branches,I updated what you mentioned in this and #2 issues.
I hope they will work.

**Comment by muhammadmnorouzi** [comment]
closed via commit <<c89d067662ce4caf048aef9873ce8b310fc8175f>>
